-- ============================================================================
-- POLI-REDI
-- PG16_0009_full_notifications.sql
--
-- Migra al runtime PostgreSQL la persistencia de notificaciones internas que
-- permanecia en la superficie FULL con consultas T-SQL.
--
-- No implementa todavia el motor de generacion de notificaciones de MVP2.
-- Solo entrega persistencia PostgreSQL compatible con la API existente y
-- preparada para categorias futuras.
-- ============================================================================

BEGIN;

SET TIME ZONE 'America/Santiago';

CREATE TABLE IF NOT EXISTS notifications (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id integer NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    reservation_id integer
        REFERENCES reservations(id)
        ON DELETE SET NULL,

    title varchar(150) NOT NULL,

    message text NOT NULL,

    type varchar(50) NOT NULL,

    is_read boolean NOT NULL DEFAULT false,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_notifications_title_nonempty
        CHECK (length(btrim(title)) > 0),

    CONSTRAINT ck_notifications_message_nonempty
        CHECK (length(btrim(message)) > 0),

    -- La etapa SQL Server utilizaba un conjunto cerrado de tipos.
    -- MVP2 preve categorias nuevas; aqui solo exigimos un valor no vacio.
    CONSTRAINT ck_notifications_type_nonempty
        CHECK (length(btrim(type)) > 0)
);

CREATE INDEX IF NOT EXISTS ix_notifications_user_read_created
    ON notifications (
        user_id,
        is_read,
        created_at DESC
    );

COMMIT;
