-- ============================================================================
-- POLI-REDI
-- PG16_0007_mvp2_schedule_exceptions.sql
--
-- MVP2 - Excepciones de ocurrencias institucionales
--
-- Objetivo:
--
-- Una regla WEEKLY representa muchas ocurrencias.
--
-- Una resolución administrativa debe poder cancelar o reprogramar UNA
-- ocurrencia concreta sin modificar toda la recurrencia.
--
-- Ejemplo:
--
--   WEEKLY martes 10:00-11:00
--
--   01 sep -> normal
--   08 sep -> CANCEL
--   15 sep -> RESCHEDULE a miércoles 14:00
--   22 sep -> normal
--
-- La regla original permanece intacta y la excepción deja trazabilidad.
-- ============================================================================

BEGIN;

SET TIME ZONE 'America/Santiago';


-- ============================================================================
-- 1. EXCEPCIONES DE OCURRENCIA
-- ============================================================================

CREATE TABLE IF NOT EXISTS institutional_activity_schedule_exceptions (

    id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    activity_id integer
        NOT NULL,

    schedule_id integer
        NOT NULL,

    -- Fecha local de la ocurrencia ORIGINAL afectada.
    original_date date
        NOT NULL,

    exception_type varchar(30)
        NOT NULL,

    -- RESCHEDULE puede trasladar la ocurrencia a otra fecha/hora.
    --
    -- CANCEL mantiene estos campos NULL.
    new_date date,

    new_start_time time,

    new_end_time time,

    created_by_user_id integer
        NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    reason text
        NOT NULL,

    created_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,


    -- ------------------------------------------------------------------------
    -- El schedule debe pertenecer a la misma actividad.
    -- ------------------------------------------------------------------------

    CONSTRAINT fk_schedule_exception_activity
        FOREIGN KEY (
            schedule_id,
            activity_id
        )
        REFERENCES institutional_activity_schedules (
            id,
            activity_id
        )
        ON DELETE CASCADE,


    CONSTRAINT ck_schedule_exception_type
        CHECK (
            exception_type IN (
                'CANCEL',
                'RESCHEDULE'
            )
        ),


    CONSTRAINT ck_schedule_exception_reason
        CHECK (
            length(trim(reason)) > 0
        ),


    -- ------------------------------------------------------------------------
    -- CANCEL
    -- ------------------------------------------------------------------------
    --
    -- La ocurrencia original desaparece y no existe reemplazo.

    CONSTRAINT ck_schedule_exception_cancel
        CHECK (
            exception_type <> 'CANCEL'
            OR (
                new_date IS NULL
                AND new_start_time IS NULL
                AND new_end_time IS NULL
            )
        ),


    -- ------------------------------------------------------------------------
    -- RESCHEDULE
    -- ------------------------------------------------------------------------
    --
    -- La ocurrencia original desaparece y se crea conceptualmente otra
    -- ocurrencia concreta en new_date/new_start_time/new_end_time.

    CONSTRAINT ck_schedule_exception_reschedule
        CHECK (
            exception_type <> 'RESCHEDULE'
            OR (
                new_date IS NOT NULL
                AND new_start_time IS NOT NULL
                AND new_end_time IS NOT NULL
                AND new_end_time > new_start_time
            )
        )
);


-- ============================================================================
-- 2. UNA SOLA DECISIÓN POR OCURRENCIA ORIGINAL
-- ============================================================================

-- Una misma ocurrencia no puede estar simultáneamente:
--
--   CANCEL
--   y
--   RESCHEDULE
--
-- Tampoco queremos dos reprogramaciones distintas para la misma ocurrencia.

CREATE UNIQUE INDEX IF NOT EXISTS
uq_institutional_schedule_exception_occurrence

ON institutional_activity_schedule_exceptions (
    schedule_id,
    original_date
);


-- ============================================================================
-- 3. CONSULTAS DE MATERIALIZACIÓN
-- ============================================================================

CREATE INDEX IF NOT EXISTS
ix_institutional_schedule_exceptions_activity

ON institutional_activity_schedule_exceptions (
    activity_id
);


CREATE INDEX IF NOT EXISTS
ix_institutional_schedule_exceptions_rescheduled_date

ON institutional_activity_schedule_exceptions (
    new_date,
    new_start_time,
    new_end_time
)

WHERE exception_type = 'RESCHEDULE';


-- ============================================================================
-- 4. UPDATED_AT
-- ============================================================================

DROP TRIGGER IF EXISTS
trg_institutional_schedule_exceptions_updated_at
ON institutional_activity_schedule_exceptions;


CREATE TRIGGER
trg_institutional_schedule_exceptions_updated_at

BEFORE UPDATE
ON institutional_activity_schedule_exceptions

FOR EACH ROW

EXECUTE FUNCTION set_updated_at();


-- ============================================================================
-- 5. INMUTABILIDAD DE LA DECISIÓN
-- ============================================================================

-- Una excepción representa el efecto histórico de una resolución
-- administrativa ya aplicada.
--
-- No debe poder transformarse posteriormente:
--
--   CANCEL -> RESCHEDULE
--   RESCHEDULE -> otra hora
--
-- Si surge una nueva incompatibilidad, debe registrarse como un nuevo
-- conflicto y una nueva decisión administrativa, no reescribir la historia.

CREATE OR REPLACE FUNCTION
prevent_schedule_exception_rewrite()
RETURNS trigger
LANGUAGE plpgsql
AS $function$

BEGIN

    IF NEW.activity_id IS DISTINCT FROM OLD.activity_id
       OR NEW.schedule_id IS DISTINCT FROM OLD.schedule_id
       OR NEW.original_date IS DISTINCT FROM OLD.original_date
       OR NEW.exception_type IS DISTINCT FROM OLD.exception_type
       OR NEW.new_date IS DISTINCT FROM OLD.new_date
       OR NEW.new_start_time IS DISTINCT FROM OLD.new_start_time
       OR NEW.new_end_time IS DISTINCT FROM OLD.new_end_time
       OR NEW.created_by_user_id IS DISTINCT FROM OLD.created_by_user_id
       OR NEW.reason IS DISTINCT FROM OLD.reason THEN

        RAISE EXCEPTION USING

            ERRCODE = '23514',

            MESSAGE =
                'una excepción de programación aplicada no puede sobrescribirse';

    END IF;


    RETURN NEW;

END
$function$;


DROP TRIGGER IF EXISTS
trg_prevent_schedule_exception_rewrite
ON institutional_activity_schedule_exceptions;


CREATE TRIGGER
trg_prevent_schedule_exception_rewrite

BEFORE UPDATE
ON institutional_activity_schedule_exceptions

FOR EACH ROW

EXECUTE FUNCTION prevent_schedule_exception_rewrite();


-- ============================================================================
-- 6. PERMISOS
-- ============================================================================

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE

ON institutional_activity_schedule_exceptions

TO poliredi_app;


GRANT USAGE, SELECT

ON SEQUENCE institutional_activity_schedule_exceptions_id_seq

TO poliredi_app;


GRANT EXECUTE

ON FUNCTION prevent_schedule_exception_rewrite()

TO poliredi_app;


COMMIT;
