BEGIN;

SET TIME ZONE 'America/Santiago';

CREATE TABLE IF NOT EXISTS venues (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL,
    address_line varchar(200),
    commune varchar(100),
    city varchar(100),
    region varchar(100),
    country varchar(100) NOT NULL DEFAULT 'Chile',
    latitude numeric(10, 7),
    longitude numeric(10, 7),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_venues_name UNIQUE (name),
    CONSTRAINT ck_venues_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_venues_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    full_name varchar(150) NOT NULL,
    rut varchar(12),
    is_admin boolean NOT NULL DEFAULT false,
    is_blocked boolean NOT NULL DEFAULT false,
    entra_oid varchar(100),
    tenant_id varchar(100),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_email_format CHECK (email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
    CONSTRAINT ck_users_rut_basic_format CHECK (rut IS NULL OR rut ~ '^[0-9]{7,8}-[0-9K]$'),
    CONSTRAINT ck_users_entra_pair CHECK (
        (entra_oid IS NULL AND tenant_id IS NULL)
        OR (entra_oid IS NOT NULL AND tenant_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS resources (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id integer NOT NULL REFERENCES venues(id) ON DELETE RESTRICT,
    name varchar(120) NOT NULL,
    type varchar(80) NOT NULL,
    reservation_mode varchar(50) NOT NULL DEFAULT 'RESERVABLE',
    image_url varchar(500),
    capacity integer,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_resources_venue_name UNIQUE (venue_id, name),
    CONSTRAINT ck_resources_mode CHECK (reservation_mode IN ('RESERVABLE', 'OPEN_USE', 'INFORMATIVE', 'ADMIN_ONLY')),
    CONSTRAINT ck_resources_capacity CHECK (capacity IS NULL OR capacity > 0)
);

CREATE TABLE IF NOT EXISTS activities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_activities_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS reservation_policies (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservable_window_days integer NOT NULL,
    request_frequency_days integer NOT NULL,
    confirmation_deadline_minutes integer NOT NULL DEFAULT 0,
    minimum_participants integer NOT NULL DEFAULT 1,
    opening_minute integer NOT NULL DEFAULT 480,
    closing_minute integer NOT NULL DEFAULT 1320,
    slot_interval_minutes integer NOT NULL DEFAULT 15,
    effective_from timestamptz NOT NULL,
    effective_to timestamptz,
    created_by_user_id integer REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idempotency_key varchar(100),
    idempotency_payload_hash char(64),
    is_published boolean NOT NULL DEFAULT true,
    CONSTRAINT ck_policies_window CHECK (reservable_window_days > 0),
    CONSTRAINT ck_policies_frequency CHECK (request_frequency_days > 0),
    CONSTRAINT ck_policies_deadline CHECK (confirmation_deadline_minutes >= 0),
    CONSTRAINT ck_policies_minimum CHECK (minimum_participants > 0),
    CONSTRAINT ck_policies_schedule CHECK (
        opening_minute >= 0
        AND opening_minute < closing_minute
        AND closing_minute <= 1440
        AND slot_interval_minutes BETWEEN 1 AND 1440
    ),
    CONSTRAINT ck_policies_effective_range CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT ck_policies_idempotency_pair CHECK (
        (idempotency_key IS NULL AND idempotency_payload_hash IS NULL)
        OR (idempotency_key IS NOT NULL AND idempotency_payload_hash IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS reservation_policy_resources (
    policy_id integer NOT NULL REFERENCES reservation_policies(id) ON DELETE CASCADE,
    resource_id integer NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    PRIMARY KEY (policy_id, resource_id)
);

CREATE TABLE IF NOT EXISTS reservation_policy_durations (
    policy_id integer NOT NULL REFERENCES reservation_policies(id) ON DELETE CASCADE,
    duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
    PRIMARY KEY (policy_id, duration_minutes)
);

CREATE TABLE IF NOT EXISTS reservations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id integer NOT NULL REFERENCES reservation_policies(id) ON DELETE RESTRICT,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    resource_id integer NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    activity_id integer REFERENCES activities(id) ON DELETE SET NULL,
    start_time timestamptz NOT NULL,
    end_time timestamptz NOT NULL,
    duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
    reservation_mode_snapshot varchar(50) NOT NULL DEFAULT 'RESERVABLE',
    status varchar(30) NOT NULL DEFAULT 'CONFIRMED',
    cancellation_reason text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reservations_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'REJECTED', 'EXPIRED')),
    CONSTRAINT ck_reservations_end CHECK (end_time > start_time),
    CONSTRAINT ck_reservations_mode_snapshot CHECK (reservation_mode_snapshot IN ('RESERVABLE', 'OPEN_USE'))
);

CREATE TABLE IF NOT EXISTS availability_blocks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id integer NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
    created_by_user_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    block_type varchar(50) NOT NULL,
    reason text,
    start_time timestamptz NOT NULL,
    end_time timestamptz NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_blocks_time CHECK (end_time > start_time),
    CONSTRAINT ck_blocks_type CHECK (block_type IN ('MAINTENANCE', 'ADMINISTRATIVE', 'EVENT', 'CLOSED', 'OTHER'))
);

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO poliredi_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO poliredi_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO poliredi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO poliredi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO poliredi_app;

COMMIT;
