-- ============================================================================
-- POLI-REDI
-- PG16_0005_mvp2_institutional_scheduling.sql
--
-- MVP2 - Programación Institucional
--
-- Objetivos:
--   1. Generalizar el antiguo concepto de EFI a unidades institucionales.
--   2. Permitir programación institucional puntual y recurrente.
--   3. Integrar clases, talleres, entrenamientos, eventos y campeonatos.
--   4. Modelar conflictos de programación con 2..N elementos.
--   5. Permitir resolución administrativa parcial o completa.
--   6. Mantener trazabilidad de las decisiones.
--   7. Preparar la arquitectura para futuras políticas automáticas.
--
-- Principios:
--
--   - EFI no es un rol especial del sistema: es una unidad académica.
--   - Los gestores actúan en representación de una unidad institucional.
--   - Una actividad institucional puede coexistir temporalmente con otras
--     actividades/reservas aunque exista conflicto.
--   - Los availability_blocks continúan representando indisponibilidad dura.
--   - Un conflicto NO modifica por sí mismo el estado de una actividad.
--   - La disponibilidad se calcula desde las ocupaciones vigentes completas,
--     no únicamente desde el intervalo donde estas se intersectan.
--   - occurrence_start / occurrence_end son snapshots históricos.
--
-- Filosofía:
--
--   PostgreSQL -> integridad estructural, relaciones y trazabilidad.
--   Go         -> permisos, detección, agrupación y resolución de conflictos.
--   Futuro     -> políticas configurables de resolución.
-- ============================================================================

BEGIN;

SET TIME ZONE 'America/Santiago';


-- ============================================================================
-- 1. UNIDADES INSTITUCIONALES
-- ============================================================================
--
-- Representan carreras, programas de postgrado, unidades deportivas,
-- unidades administrativas u otras organizaciones autorizadas a utilizar
-- institucionalmente los recursos del polideportivo.
--
-- Ejemplos:
--
--   Educación Física
--   Preparación Física
--   Magíster en Actividad Física
--   Deportes UCEN
--
-- No se crea una columna o rol específico "EFI"; Educación Física será
-- simplemente una instancia de esta entidad.
-- ============================================================================

CREATE TABLE IF NOT EXISTS institutional_units (

    id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    name varchar(150)
        NOT NULL,

    code varchar(50)
        NOT NULL,

    unit_type varchar(50)
        NOT NULL,

    is_active boolean
        NOT NULL DEFAULT true,

    created_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_institutional_units_name
        CHECK (length(trim(name)) > 0),

    CONSTRAINT ck_institutional_units_code
        CHECK (length(trim(code)) > 0),

    CONSTRAINT ck_institutional_units_type
        CHECK (
            unit_type IN (
                'ACADEMIC_PROGRAM',
                'POSTGRADUATE_PROGRAM',
                'SPORTS_UNIT',
                'ADMINISTRATIVE_UNIT',
                'OTHER'
            )
        )
);


-- Los nombres y códigos se comparan sin distinguir mayúsculas/minúsculas.
-- Esto evita, por ejemplo, registrar simultáneamente "EFI" y "efi".

CREATE UNIQUE INDEX IF NOT EXISTS uq_institutional_units_name_ci
    ON institutional_units (lower(name));

CREATE UNIQUE INDEX IF NOT EXISTS uq_institutional_units_code_ci
    ON institutional_units (lower(code));

CREATE INDEX IF NOT EXISTS ix_institutional_units_active
    ON institutional_units (is_active)
    WHERE is_active = true;


-- ============================================================================
-- 2. MEMBRESÍAS / GESTORES DE UNIDAD
-- ============================================================================
--
-- Relaciona usuarios con unidades institucionales.
--
-- MEMBER:
--   pertenece a la unidad, pero no obtiene automáticamente permisos de
--   programación.
--
-- MANAGER:
--   puede gestionar programación institucional de la unidad.
--
-- Los administradores globales siguen siendo controlados por users.is_admin
-- y no necesitan una membresía en cada unidad.
-- ============================================================================

CREATE TABLE IF NOT EXISTS institutional_unit_memberships (

    id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    unit_id integer
        NOT NULL
        REFERENCES institutional_units(id)
        ON DELETE RESTRICT,

    user_id integer
        NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    role varchar(30)
        NOT NULL DEFAULT 'MEMBER',

    is_active boolean
        NOT NULL DEFAULT true,

    created_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_institutional_unit_membership
        UNIQUE (unit_id, user_id),

    CONSTRAINT ck_institutional_unit_membership_role
        CHECK (
            role IN (
                'MEMBER',
                'MANAGER'
            )
        )
);


CREATE INDEX IF NOT EXISTS ix_institutional_memberships_user
    ON institutional_unit_memberships (user_id);

CREATE INDEX IF NOT EXISTS ix_institutional_memberships_managers
    ON institutional_unit_memberships (unit_id, user_id)
    WHERE is_active = true
      AND role = 'MANAGER';


-- ============================================================================
-- 3. ACTIVIDADES INSTITUCIONALES
-- ============================================================================
--
-- Entidad principal del módulo.
--
-- Tipos iniciales:
--
--   ACADEMIC_CLASS -> clase curricular
--   WORKSHOP       -> taller con inscripción
--   TRAINING       -> entrenamiento
--   EVENT          -> evento institucional
--   CHAMPIONSHIP   -> campeonato
--   OTHER          -> otros usos autorizados
--
-- El tipo no determina automáticamente prioridad.
-- Las prioridades serán resueltas administrativamente durante MVP2 y podrán
-- ser gobernadas posteriormente mediante políticas configurables.
-- ============================================================================

CREATE TABLE IF NOT EXISTS institutional_activities (

    id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    unit_id integer
        NOT NULL
        REFERENCES institutional_units(id)
        ON DELETE RESTRICT,

    resource_id integer
        NOT NULL
        REFERENCES resources(id)
        ON DELETE RESTRICT,

    activity_type varchar(50)
        NOT NULL,

    title varchar(150)
        NOT NULL,

    description text,

    status varchar(30)
        NOT NULL DEFAULT 'DRAFT',

    -- Las actividades que requieren inscripción deben declarar capacidad.
    -- WORKSHOP exige inscripción, pero el modelo permite que en el futuro
    -- otros tipos también puedan utilizar este mecanismo.

    requires_enrollment boolean
        NOT NULL DEFAULT false,

    capacity integer,

    created_by_user_id integer
        NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    created_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_institutional_activity_type
        CHECK (
            activity_type IN (
                'ACADEMIC_CLASS',
                'WORKSHOP',
                'TRAINING',
                'EVENT',
                'CHAMPIONSHIP',
                'OTHER'
            )
        ),

    CONSTRAINT ck_institutional_activity_status
        CHECK (
            status IN (
                'DRAFT',
                'SCHEDULED',
                'CANCELLED',
                'COMPLETED'
            )
        ),

    CONSTRAINT ck_institutional_activity_title
        CHECK (length(trim(title)) > 0),

    -- Si existe inscripción debe existir una capacidad positiva.
    -- Si no existe inscripción no mantenemos una capacidad sin significado.

    CONSTRAINT ck_institutional_activity_enrollment_capacity
        CHECK (
            (
                requires_enrollment = true
                AND capacity IS NOT NULL
                AND capacity > 0
            )
            OR
            (
                requires_enrollment = false
                AND capacity IS NULL
            )
        ),

    -- Todo WORKSHOP debe usar el flujo de inscripción.

    CONSTRAINT ck_institutional_activity_workshop
        CHECK (
            activity_type <> 'WORKSHOP'
            OR requires_enrollment = true
        )
);


CREATE INDEX IF NOT EXISTS ix_institutional_activities_unit
    ON institutional_activities (unit_id);

CREATE INDEX IF NOT EXISTS ix_institutional_activities_resource
    ON institutional_activities (resource_id);

CREATE INDEX IF NOT EXISTS ix_institutional_activities_scheduled
    ON institutional_activities (resource_id, status)
    WHERE status = 'SCHEDULED';


-- ============================================================================
-- 4. PROGRAMACIÓN DE ACTIVIDADES
-- ============================================================================
--
-- Una actividad puede tener múltiples reglas de horario.
--
-- SINGLE:
--
--   actividad puntual.
--
--   specific_date obligatorio.
--   day_of_week, valid_from y valid_to deben ser NULL.
--
-- WEEKLY:
--
--   recurrencia semanal estructurada.
--
--   day_of_week usa ISO 8601:
--
--       1 = lunes
--       2 = martes
--       ...
--       7 = domingo
--
--   valid_from y valid_to delimitan el período de recurrencia.
--
-- Los horarios almacenados son horas locales del recinto.
-- Al generar una ocurrencia concreta, Go la convierte a timestamptz usando
-- APP_TIMEZONE / America/Santiago.
--
-- No se permiten actividades que crucen medianoche en MVP2.
-- ============================================================================

CREATE TABLE IF NOT EXISTS institutional_activity_schedules (

    id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    activity_id integer
        NOT NULL
        REFERENCES institutional_activities(id)
        ON DELETE CASCADE,

    schedule_type varchar(20)
        NOT NULL,

    specific_date date,

    day_of_week smallint,

    start_time time
        NOT NULL,

    end_time time
        NOT NULL,

    valid_from date,

    valid_to date,

    is_active boolean
        NOT NULL DEFAULT true,

    created_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_institutional_schedule_type
        CHECK (
            schedule_type IN (
                'SINGLE',
                'WEEKLY'
            )
        ),

    CONSTRAINT ck_institutional_schedule_time
        CHECK (end_time > start_time),

    CONSTRAINT ck_institutional_schedule_day
        CHECK (
            day_of_week IS NULL
            OR day_of_week BETWEEN 1 AND 7
        ),

    -- SINGLE representa exactamente una fecha concreta.

    CONSTRAINT ck_institutional_schedule_single
        CHECK (
            schedule_type <> 'SINGLE'
            OR (
                specific_date IS NOT NULL
                AND day_of_week IS NULL
                AND valid_from IS NULL
                AND valid_to IS NULL
            )
        ),

    -- WEEKLY representa una regla de recurrencia acotada.
    -- Para MVP2 se exige fecha inicial y final explícita; evitamos así
    -- recurrencias institucionales infinitas.

    CONSTRAINT ck_institutional_schedule_weekly
        CHECK (
            schedule_type <> 'WEEKLY'
            OR (
                specific_date IS NULL
                AND day_of_week IS NOT NULL
                AND valid_from IS NOT NULL
                AND valid_to IS NOT NULL
                AND valid_to >= valid_from
            )
        ),

    -- Permite que scheduling_conflict_items pueda validar mediante una FK
    -- compuesta que el schedule realmente pertenece a la actividad indicada.

    CONSTRAINT uq_institutional_schedule_activity
        UNIQUE (id, activity_id)
);


CREATE INDEX IF NOT EXISTS ix_institutional_schedules_activity
    ON institutional_activity_schedules (activity_id);

CREATE INDEX IF NOT EXISTS ix_institutional_schedules_single
    ON institutional_activity_schedules (
        specific_date,
        start_time,
        end_time
    )
    WHERE is_active = true
      AND schedule_type = 'SINGLE';

CREATE INDEX IF NOT EXISTS ix_institutional_schedules_weekly
    ON institutional_activity_schedules (
        day_of_week,
        valid_from,
        valid_to,
        start_time,
        end_time
    )
    WHERE is_active = true
      AND schedule_type = 'WEEKLY';


-- Evita duplicar exactamente la misma programación puntual dentro de
-- una actividad.

CREATE UNIQUE INDEX IF NOT EXISTS uq_institutional_schedule_single
    ON institutional_activity_schedules (
        activity_id,
        specific_date,
        start_time,
        end_time
    )
    WHERE schedule_type = 'SINGLE'
      AND is_active = true;


-- Evita duplicar exactamente la misma recurrencia semanal activa.

CREATE UNIQUE INDEX IF NOT EXISTS uq_institutional_schedule_weekly
    ON institutional_activity_schedules (
        activity_id,
        day_of_week,
        start_time,
        end_time,
        valid_from,
        valid_to
    )
    WHERE schedule_type = 'WEEKLY'
      AND is_active = true;


-- ============================================================================
-- 5. INSCRIPCIONES A ACTIVIDADES
-- ============================================================================
--
-- Reemplaza conceptualmente el antiguo workshop_enrollments.
--
-- Inicialmente será utilizado principalmente por WORKSHOP.
--
-- La capacidad máxima NO se implementa aquí mediante COUNT() + CHECK porque
-- dicha comprobación no sería segura frente a concurrencia.
--
-- El repositorio Go realizará la inscripción dentro de una transacción
-- SERIALIZABLE bloqueando la actividad antes de contar cupos.
-- ============================================================================

CREATE TABLE IF NOT EXISTS institutional_activity_enrollments (

    id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    activity_id integer
        NOT NULL
        REFERENCES institutional_activities(id)
        ON DELETE RESTRICT,

    user_id integer
        NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    status varchar(30)
        NOT NULL DEFAULT 'CONFIRMED',

    created_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_institutional_activity_enrollment
        UNIQUE (activity_id, user_id),

    CONSTRAINT ck_institutional_activity_enrollment_status
        CHECK (
            status IN (
                'CONFIRMED',
                'CANCELLED'
            )
        )
);


CREATE INDEX IF NOT EXISTS ix_institutional_enrollments_activity
    ON institutional_activity_enrollments (activity_id);

CREATE INDEX IF NOT EXISTS ix_institutional_enrollments_user
    ON institutional_activity_enrollments (user_id);

CREATE INDEX IF NOT EXISTS ix_institutional_enrollments_confirmed
    ON institutional_activity_enrollments (activity_id)
    WHERE status = 'CONFIRMED';


-- ============================================================================
-- 6. GRUPOS DE CONFLICTO DE PROGRAMACIÓN
-- ============================================================================
--
-- Un conflicto NO representa únicamente A <-> B.
--
-- Puede representar un conjunto conectado de 2..N ocupaciones incompatibles.
--
-- Ejemplo:
--
--   A  10:00 - 11:30
--   B  10:30 - 12:00
--   C  11:00 - 13:00
--
-- Las intersecciones internas son distintas, pero las tres ocupaciones
-- pueden pertenecer al mismo grupo de conflicto.
--
-- La disponibilidad para terceros se deriva de las ocupaciones vigentes,
-- por lo que en el ejemplo el recurso permanece ocupado de 10:00 a 13:00.
--
-- No almacenamos activity_a/activity_b para no limitar el modelo a pares.
-- ============================================================================

CREATE TABLE IF NOT EXISTS scheduling_conflicts (

    id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    resource_id integer
        NOT NULL
        REFERENCES resources(id)
        ON DELETE RESTRICT,

    status varchar(30)
        NOT NULL DEFAULT 'PENDING',

    -- Durante MVP2 la resolución será MANUAL.
    -- POLICY y MIXED dejan preparado el modelo para futuras reglas automáticas.

    resolution_source varchar(30),

    resolution_summary text,

    resolved_by_user_id integer
        REFERENCES users(id)
        ON DELETE RESTRICT,

    resolved_at timestamptz,

    created_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_scheduling_conflict_status
        CHECK (
            status IN (
                'PENDING',
                'RESOLVED'
            )
        ),

    CONSTRAINT ck_scheduling_conflict_resolution_source
        CHECK (
            resolution_source IS NULL
            OR resolution_source IN (
                'MANUAL',
                'POLICY',
                'MIXED'
            )
        ),

    -- Un conflicto pendiente todavía no tiene resolución global.
    -- Un conflicto resuelto debe indicar cuándo y mediante qué mecanismo
    -- terminó el proceso de resolución.

    CONSTRAINT ck_scheduling_conflict_resolution_metadata
        CHECK (
            (
                status = 'PENDING'
                AND resolution_source IS NULL
                AND resolved_at IS NULL
            )
            OR
            (
                status = 'RESOLVED'
                AND resolution_source IS NOT NULL
                AND resolved_at IS NOT NULL
            )
        ),

    -- Una resolución global puramente manual debe identificar al usuario
    -- responsable del cierre.

    CONSTRAINT ck_scheduling_conflict_manual_resolver
        CHECK (
            resolution_source <> 'MANUAL'
            OR resolved_by_user_id IS NOT NULL
        )
);


CREATE INDEX IF NOT EXISTS ix_scheduling_conflicts_resource
    ON scheduling_conflicts (resource_id);

CREATE INDEX IF NOT EXISTS ix_scheduling_conflicts_pending
    ON scheduling_conflicts (resource_id, created_at)
    WHERE status = 'PENDING';


-- ============================================================================
-- 7. ELEMENTOS DEL CONFLICTO
-- ============================================================================
--
-- Cada conflicto puede contener N elementos.
--
-- Un elemento puede representar:
--
--   - una ocurrencia concreta de una actividad institucional;
--   - una reserva particular.
--
-- Evitamos entity_type/entity_id polimórficos porque perderíamos integridad
-- referencial. En su lugar usamos dos FKs opcionales con una restricción XOR.
--
-- Para una actividad institucional:
--
--   institutional_activity_id NOT NULL
--   schedule_id               NOT NULL
--   reservation_id            NULL
--
-- Para una reserva:
--
--   institutional_activity_id NULL
--   schedule_id               NULL
--   reservation_id            NOT NULL
--
-- occurrence_start y occurrence_end son SNAPSHOTS HISTÓRICOS.
--
-- Aunque el horario pueda reconstruirse desde schedule_id, una regla
-- recurrente puede producir muchas ocurrencias y además podría ser modificada
-- posteriormente. El snapshot conserva exactamente el intervalo que participó
-- en el conflicto cuando este fue detectado.
-- ============================================================================

CREATE TABLE IF NOT EXISTS scheduling_conflict_items (

    id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    conflict_id integer
        NOT NULL
        REFERENCES scheduling_conflicts(id)
        ON DELETE CASCADE,

    institutional_activity_id integer
        REFERENCES institutional_activities(id)
        ON DELETE RESTRICT,

    schedule_id integer,

    reservation_id integer
        REFERENCES reservations(id)
        ON DELETE RESTRICT,

    occurrence_start timestamptz
        NOT NULL,

    occurrence_end timestamptz
        NOT NULL,

    -- La decisión se almacena por elemento para soportar conflictos N-elementos
    -- y resoluciones parciales.
    --
    -- Ejemplo:
    --
    --   A -> ALLOW
    --   B -> ALLOW
    --   C -> RESCHEDULE
    --
    -- Con dos elementos, ALLOW + ALLOW equivale funcionalmente a ALLOW_BOTH.

    resolution varchar(30)
        NOT NULL DEFAULT 'PENDING',

    resolution_source varchar(30),

    resolved_by_user_id integer
        REFERENCES users(id)
        ON DELETE RESTRICT,

    resolved_at timestamptz,

    resolution_note text,

    created_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamptz
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_conflict_item_schedule_activity
        FOREIGN KEY (
            schedule_id,
            institutional_activity_id
        )
        REFERENCES institutional_activity_schedules (
            id,
            activity_id
        )
        ON DELETE RESTRICT,

    CONSTRAINT ck_scheduling_conflict_item_entity
        CHECK (
            (
                institutional_activity_id IS NOT NULL
                AND schedule_id IS NOT NULL
                AND reservation_id IS NULL
            )
            OR
            (
                institutional_activity_id IS NULL
                AND schedule_id IS NULL
                AND reservation_id IS NOT NULL
            )
        ),

    CONSTRAINT ck_scheduling_conflict_item_occurrence
        CHECK (occurrence_end > occurrence_start),

    CONSTRAINT ck_scheduling_conflict_item_resolution
        CHECK (
            resolution IN (
                'PENDING',
                'KEEP',
                'ALLOW',
                'RESCHEDULE',
                'CANCEL'
            )
        ),

    CONSTRAINT ck_scheduling_conflict_item_resolution_source
        CHECK (
            resolution_source IS NULL
            OR resolution_source IN (
                'MANUAL',
                'POLICY'
            )
        ),

    -- Mientras el elemento esté pendiente no puede aparentar una resolución.
    -- Cuando exista una decisión, esta debe indicar cuándo y cómo se tomó.

    CONSTRAINT ck_scheduling_conflict_item_resolution_metadata
        CHECK (
            (
                resolution = 'PENDING'
                AND resolution_source IS NULL
                AND resolved_by_user_id IS NULL
                AND resolved_at IS NULL
            )
            OR
            (
                resolution <> 'PENDING'
                AND resolution_source IS NOT NULL
                AND resolved_at IS NOT NULL
            )
        ),

    -- Las decisiones manuales deben identificar quién las tomó.
    -- Una política automática futura podrá no tener resolved_by_user_id.

    CONSTRAINT ck_scheduling_conflict_item_manual_resolver
        CHECK (
            resolution_source <> 'MANUAL'
            OR resolved_by_user_id IS NOT NULL
        )
);


CREATE INDEX IF NOT EXISTS ix_scheduling_conflict_items_conflict
    ON scheduling_conflict_items (conflict_id);

CREATE INDEX IF NOT EXISTS ix_scheduling_conflict_items_activity
    ON scheduling_conflict_items (
        institutional_activity_id,
        occurrence_start,
        occurrence_end
    )
    WHERE institutional_activity_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_scheduling_conflict_items_reservation
    ON scheduling_conflict_items (reservation_id)
    WHERE reservation_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_scheduling_conflict_items_pending
    ON scheduling_conflict_items (conflict_id)
    WHERE resolution = 'PENDING';


-- Una misma ocurrencia de actividad no debe aparecer dos veces dentro
-- del mismo grupo de conflicto.

CREATE UNIQUE INDEX IF NOT EXISTS uq_conflict_item_activity_occurrence
    ON scheduling_conflict_items (
        conflict_id,
        institutional_activity_id,
        schedule_id,
        occurrence_start
    )
    WHERE institutional_activity_id IS NOT NULL;


-- Una reserva tampoco debe repetirse dentro del mismo grupo.

CREATE UNIQUE INDEX IF NOT EXISTS uq_conflict_item_reservation
    ON scheduling_conflict_items (
        conflict_id,
        reservation_id
    )
    WHERE reservation_id IS NOT NULL;


-- ============================================================================
-- 8. INVARIANTE: TODOS LOS ELEMENTOS PERTENECEN AL RECURSO DEL CONFLICTO
-- ============================================================================
--
-- scheduling_conflicts agrupa conflictos por recurso.
--
-- Esta validación evita, por ejemplo, introducir accidentalmente una reserva
-- de Cancha 2 dentro de un conflicto correspondiente a Cancha 1.
--
-- La detección y agrupación siguen siendo responsabilidad del servicio Go;
-- PostgreSQL protege la coherencia estructural del resultado.
-- ============================================================================

CREATE OR REPLACE FUNCTION validate_scheduling_conflict_item()
RETURNS trigger
LANGUAGE plpgsql
AS $function$

DECLARE

    v_conflict_resource_id integer;
    v_entity_resource_id integer;

BEGIN

    SELECT conflict.resource_id
    INTO v_conflict_resource_id
    FROM scheduling_conflicts conflict
    WHERE conflict.id = NEW.conflict_id;


    IF NEW.institutional_activity_id IS NOT NULL THEN

        SELECT activity.resource_id
        INTO v_entity_resource_id
        FROM institutional_activities activity
        WHERE activity.id = NEW.institutional_activity_id;

    ELSE

        SELECT reservation.resource_id
        INTO v_entity_resource_id
        FROM reservations reservation
        WHERE reservation.id = NEW.reservation_id;

    END IF;


    -- Las FKs normalmente detectarán entidades inexistentes.
    -- Este control protege específicamente la coherencia del recurso.

    IF v_conflict_resource_id IS DISTINCT FROM v_entity_resource_id THEN

        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'el elemento del conflicto no pertenece al recurso del conflicto';

    END IF;


    RETURN NEW;

END
$function$;


DROP TRIGGER IF EXISTS trg_validate_scheduling_conflict_item
    ON scheduling_conflict_items;


CREATE TRIGGER trg_validate_scheduling_conflict_item

BEFORE INSERT OR UPDATE OF
    conflict_id,
    institutional_activity_id,
    schedule_id,
    reservation_id

ON scheduling_conflict_items

FOR EACH ROW
EXECUTE FUNCTION validate_scheduling_conflict_item();


-- ============================================================================
-- 9. INVARIANTE: UN CONFLICTO NO PUEDE CERRARSE CON ELEMENTOS PENDIENTES
-- ============================================================================
--
-- Las resoluciones pueden ser parciales.
--
-- Por ejemplo:
--
--   A -> ALLOW
--   B -> ALLOW
--   C -> PENDING
--
-- El grupo completo continúa PENDING hasta resolver C.
--
-- Cuando la resolución origine una reprogramación, el servicio deberá volver
-- a ejecutar la detección de conflictos sobre la nueva programación.
-- ============================================================================

CREATE OR REPLACE FUNCTION validate_scheduling_conflict_resolution()
RETURNS trigger
LANGUAGE plpgsql
AS $function$

BEGIN

    -- Los conflictos resueltos se conservan como registro histórico.
    -- Si vuelve a existir una incompatibilidad, se crea un nuevo conflicto
    -- en lugar de reabrir silenciosamente el anterior.

    IF TG_OP = 'UPDATE'
       AND OLD.status = 'RESOLVED'
       AND NEW.status = 'PENDING' THEN

        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'un conflicto resuelto no puede volver al estado pendiente';

    END IF;


    IF NEW.status = 'RESOLVED'
       AND EXISTS (
            SELECT 1
            FROM scheduling_conflict_items item
            WHERE item.conflict_id = NEW.id
              AND item.resolution = 'PENDING'
       ) THEN

        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'no se puede cerrar un conflicto con elementos pendientes';

    END IF;


    RETURN NEW;

END
$function$;


DROP TRIGGER IF EXISTS trg_validate_scheduling_conflict_resolution
    ON scheduling_conflicts;


CREATE TRIGGER trg_validate_scheduling_conflict_resolution

BEFORE UPDATE OF status
ON scheduling_conflicts

FOR EACH ROW
EXECUTE FUNCTION validate_scheduling_conflict_resolution();


-- ============================================================================
-- 10. TRAZABILIDAD DE DECISIONES POR ELEMENTO
-- ============================================================================
--
-- Una decisión ya aplicada dentro de un conflicto no se sobrescribe.
--
-- Si después de KEEP/ALLOW/RESCHEDULE/CANCEL aparece una nueva
-- incompatibilidad, el detector debe crear un nuevo conflicto.
--
-- Esto evita modificar retroactivamente la decisión administrativa que quedó
-- registrada originalmente.
-- ============================================================================

CREATE OR REPLACE FUNCTION prevent_conflict_item_resolution_rewrite()
RETURNS trigger
LANGUAGE plpgsql
AS $function$

BEGIN

    IF OLD.resolution <> 'PENDING'
       AND (
            NEW.resolution IS DISTINCT FROM OLD.resolution
            OR NEW.resolution_source IS DISTINCT FROM OLD.resolution_source
            OR NEW.resolved_by_user_id IS DISTINCT FROM OLD.resolved_by_user_id
            OR NEW.resolved_at IS DISTINCT FROM OLD.resolved_at
            OR NEW.resolution_note IS DISTINCT FROM OLD.resolution_note
       ) THEN

        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'una resolución de conflicto aplicada no puede sobrescribirse';

    END IF;


    RETURN NEW;

END
$function$;


DROP TRIGGER IF EXISTS trg_prevent_conflict_item_resolution_rewrite
    ON scheduling_conflict_items;


CREATE TRIGGER trg_prevent_conflict_item_resolution_rewrite

BEFORE UPDATE OF
    resolution,
    resolution_source,
    resolved_by_user_id,
    resolved_at,
    resolution_note

ON scheduling_conflict_items

FOR EACH ROW
EXECUTE FUNCTION prevent_conflict_item_resolution_rewrite();


-- ============================================================================
-- 11. UPDATED_AT
-- ============================================================================
--
-- Reutilizamos set_updated_at(), creada por PG16_0003.
-- ============================================================================

DROP TRIGGER IF EXISTS trg_institutional_units_updated_at
    ON institutional_units;

CREATE TRIGGER trg_institutional_units_updated_at

BEFORE UPDATE
ON institutional_units

FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


DROP TRIGGER IF EXISTS trg_institutional_memberships_updated_at
    ON institutional_unit_memberships;

CREATE TRIGGER trg_institutional_memberships_updated_at

BEFORE UPDATE
ON institutional_unit_memberships

FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


DROP TRIGGER IF EXISTS trg_institutional_activities_updated_at
    ON institutional_activities;

CREATE TRIGGER trg_institutional_activities_updated_at

BEFORE UPDATE
ON institutional_activities

FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


DROP TRIGGER IF EXISTS trg_institutional_schedules_updated_at
    ON institutional_activity_schedules;

CREATE TRIGGER trg_institutional_schedules_updated_at

BEFORE UPDATE
ON institutional_activity_schedules

FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


DROP TRIGGER IF EXISTS trg_institutional_enrollments_updated_at
    ON institutional_activity_enrollments;

CREATE TRIGGER trg_institutional_enrollments_updated_at

BEFORE UPDATE
ON institutional_activity_enrollments

FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


DROP TRIGGER IF EXISTS trg_scheduling_conflicts_updated_at
    ON scheduling_conflicts;

CREATE TRIGGER trg_scheduling_conflicts_updated_at

BEFORE UPDATE
ON scheduling_conflicts

FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


DROP TRIGGER IF EXISTS trg_scheduling_conflict_items_updated_at
    ON scheduling_conflict_items;

CREATE TRIGGER trg_scheduling_conflict_items_updated_at

BEFORE UPDATE
ON scheduling_conflict_items

FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ============================================================================
-- 12. PERMISOS
-- ============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE
ON institutional_units
TO poliredi_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON institutional_unit_memberships
TO poliredi_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON institutional_activities
TO poliredi_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON institutional_activity_schedules
TO poliredi_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON institutional_activity_enrollments
TO poliredi_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON scheduling_conflicts
TO poliredi_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON scheduling_conflict_items
TO poliredi_app;


-- Las tablas utilizan columnas IDENTITY.
-- La migración base ya establece default privileges para nuevas secuencias,
-- pero se concede explícitamente acceso a todas las secuencias del esquema
-- para mantener consistente el entorno de prueba y despliegue.

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO poliredi_app;


GRANT EXECUTE
ON FUNCTION validate_scheduling_conflict_item()
TO poliredi_app;

GRANT EXECUTE
ON FUNCTION validate_scheduling_conflict_resolution()
TO poliredi_app;

GRANT EXECUTE
ON FUNCTION prevent_conflict_item_resolution_rewrite()
TO poliredi_app;


COMMIT;
